// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2GyyV1uN4xbnqKtJ7pjrQU
// Component: V6AvhSaRTMLUNb
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_e_commerce.module.css"; // plasmic-import: 2GyyV1uN4xbnqKtJ7pjrQU/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: V6AvhSaRTMLUNb/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: W0U4FGNvH3vD6W/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicRatings__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],

    [$props, $ctx]
  );

  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant($state, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__el59T, {
              [sty.svgstars_five__el59Tk1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_zero__el59TQkr0L]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__oiXcR, {
              [sty.svgstars_five__oiXcRk1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four__oiXcRTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_one__oiXcRo9WbA]: hasVariant(
                $state,
                "stars",
                "one"
              ),

              [sty.svgstars_three__oiXcRAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              ),

              [sty.svgstars_two__oiXcRlWyyw]: hasVariant(
                $state,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__oiXcRQkr0L]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__jRdma, {
              [sty.svgstars_five__jRdmak1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four__jRdmaTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_one__jRdmAo9WbA]: hasVariant(
                $state,
                "stars",
                "one"
              ),

              [sty.svgstars_three__jRdmaAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              ),

              [sty.svgstars_two__jRdmalWyyw]: hasVariant(
                $state,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__jRdmaQkr0L]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__eGrSm, {
              [sty.svgstars_five__eGrSmK1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four__eGrSmTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_one__eGrSmo9WbA]: hasVariant(
                $state,
                "stars",
                "one"
              ),

              [sty.svgstars_three__eGrSmAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              ),

              [sty.svgstars_two__eGrSmLWyyw]: hasVariant(
                $state,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__eGrSmQkr0L]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__mzqZq, {
              [sty.svgstars_five__mzqZqk1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four__mzqZqTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_one__mzqZQo9WbA]: hasVariant(
                $state,
                "stars",
                "one"
              ),

              [sty.svgstars_three__mzqZqAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              ),

              [sty.svgstars_two__mzqZqlWyyw]: hasVariant(
                $state,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__mzqZqQkr0L]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___0KXhU, {
              [sty.svgstars_five___0KXhUk1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four___0KXhUTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_one___0KXhUo9WbA]: hasVariant(
                $state,
                "stars",
                "one"
              ),

              [sty.svgstars_three___0KXhUAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              ),

              [sty.svgstars_two___0KXhUlWyyw]: hasVariant(
                $state,
                "stars",
                "two"
              ),

              [sty.svgstars_zero___0KXhUQkr0L]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__vvEtk, {
              [sty.svgstars_five__vvEtkK1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four__vvEtkTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_three__vvEtkAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              ),

              [sty.svgstars_two__vvEtkLWyyw]: hasVariant($state, "stars", "two")
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__lP4Yt, {
              [sty.svgstars_five__lP4YtK1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four__lP4YtTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              ),

              [sty.svgstars_three__lP4YtAJuk]: hasVariant(
                $state,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___4UjFe, {
              [sty.svgstars_five___4UjFeK1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              ),

              [sty.svgstars_four___4UjFeTjndY]: hasVariant(
                $state,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant($state, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__yp67N, {
              [sty.svgstars_five__yp67NK1Dxe]: hasVariant(
                $state,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>
      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
