// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2GyyV1uN4xbnqKtJ7pjrQU
// Component: 45CXakC6GRGfb8
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantscf27W7HxUbhqT } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: -CF27w7hxUbhqT/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_e_commerce.module.css"; // plasmic-import: 2GyyV1uN4xbnqKtJ7pjrQU/projectcss
import sty from "./PlasmicProductRow.module.css"; // plasmic-import: 45CXakC6GRGfb8/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: Z9yWUb_XEPOXSj/icon
import plant1FeaturedjpgCpgtDGkIKqT9Aq from "./images/plant1Featuredjpg.png"; // plasmic-import: cpgtDGkIKqT9AQ/picture
import plant2FeaturedjpgNbHh753Gorbpp0 from "./images/plant2Featuredjpg.png"; // plasmic-import: NBHh753Gorbpp0/picture
import plant5FeaturedjpgIgAcBQiM5Dwuip from "./images/plant5Featuredjpg.png"; // plasmic-import: IGAcBQiM5dwuip/picture
import acquapngVm8DXQ6U from "./images/acquapng.png"; // plasmic-import: Vm8d_xQ6u/picture

export const PlasmicProductRow__VariantProps = new Array();

export const PlasmicProductRow__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicProductRow__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscf27W7HxUbhqT()
  });
  return true ? (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column__q2Qs)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__dTTmT)}
          displayHeight={"270px /* plasmic-token: FrVxrO3xIVC8IA */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant1FeaturedjpgCpgtDGkIKqT9Aq,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__ud3Gr)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg__nqozm)}
              role={"img"}
            />
          </div>
        ) : null}
        <div className={classNames(projectcss.all, sty.freeBox__u0Fwv)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___9HfH
            )}
          >
            {"piantina grassa"}
          </a>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__stJht
            )}
          >
            {"PIANTE"}
          </div>
          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5___8ZrPq
            )}
          >
            {"$9.40 "}
          </h5>
        </div>
      </p.Stack>
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column__zetnz)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__uh5F)}
          displayHeight={"270px /* plasmic-token: FrVxrO3xIVC8IA */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant2FeaturedjpgNbHh753Gorbpp0,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__e2Zdu)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg___9Iy9D)}
              role={"img"}
            />
          </div>
        ) : null}
        <div className={classNames(projectcss.all, sty.freeBox__skgk)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__gLZsI
            )}
          >
            {"Gelsomino"}
          </a>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___7Ghhx
            )}
          >
            {"FIORE"}
          </div>
          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5___8FS3D
            )}
          >
            {"$3.00 "}
          </h5>
        </div>
      </p.Stack>
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column__zXcMa)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__se4Gf)}
          displayHeight={"270px /* plasmic-token: FrVxrO3xIVC8IA */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant5FeaturedjpgIgAcBQiM5Dwuip,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__kdWCe)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg__p9QHw)}
              role={"img"}
            />
          </div>
        ) : null}
        <div className={classNames(projectcss.all, sty.freeBox___4Nmbo)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__aklUx
            )}
          >
            {"Edera"}
          </a>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___8Of7
            )}
          >
            {"PIANTA"}
          </div>
          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5___0Flex
            )}
          >
            {"$220.00 "}
          </h5>
        </div>
      </p.Stack>
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column__yHfbg)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__qlfXg)}
          displayHeight={"270px /* plasmic-token: FrVxrO3xIVC8IA */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: acquapngVm8DXQ6U,
            fullWidth: 381,
            fullHeight: 1093,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__wWgRq)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg__dbawX)}
              role={"img"}
            />
          </div>
        ) : null}
        <div className={classNames(projectcss.all, sty.freeBox__bcHmi)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__xcZwl
            )}
          >
            {"Acqua"}
          </a>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hv9T8
            )}
          >
            {"BIBITA"}
          </div>
          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5__dle82
            )}
          >
            {"$1.00 "}
          </h5>
        </div>
      </p.Stack>
    </p.Stack>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProductRow__ArgProps,
          internalVariantPropNames: PlasmicProductRow__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicProductRow__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductRow";
  } else {
    func.displayName = `PlasmicProductRow.${nodeName}`;
  }
  return func;
}

export const PlasmicProductRow = Object.assign(
  // Top-level PlasmicProductRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicProductRow
    internalVariantProps: PlasmicProductRow__VariantProps,
    internalArgProps: PlasmicProductRow__ArgProps
  }
);

export default PlasmicProductRow;
/* prettier-ignore-end */
